name: Deploy Network Diagram Studio
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
 
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Configure Pages
        uses: actions/configure-pages@v5
 
      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./Network-Diagram-Studio-GitHub
 
  deploy:
    environment:
      name: github-pages
 
    runs-on: ubuntu-latest
    needs: build
 
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
